### ISSUE TITLE
Upgrade tests 2.0

### ISSUE THREAD

**Issue by JohnKhandygo** [gnatunstyles/ProkofyevIgnatJavaProject1#10]
- [x] (3) Во-первых, Ваши тесты у меня не работают из-за того, что тестовые файлы имеют отличные от ожидаемых времена модификации (на моей машине эти файлы были созданы в момент клонирования проекта).
- [ ] (5) Тесты будут работать только для такой же файловой системе, как и у Вас. В любой другой размеры файлов могут отличаться от ожидаемых.
- [ ] (4) Входные/выходные тестовые файлы принято размещать в директории тестовых ресурсов (в соответствии со [стандартной структурой](https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html) maven проектов)
- [x] (4) После исполнения тестов в дереве проекта появляются лишние файлы. Эти файлы необходимо либо удалять после прогона тестов, либо размещать в какой-нибудь временной директории.

**Comment by gnatunstyles** [comment]
@JohnKhandygo 
отправил фиксы 2го.

**Comment by JohnKhandygo** [comment]
- [ ] (3) У меня не работают тесты `testHumanReadable` и `testHumanReadable2`.

**Comment by gnatunstyles** [comment]
@JohnKhandygo 
Я не могу понять, в чем там ошибка. Не могли бы Вы скинуть отчет об ошибке?

**Comment by gnatunstyles** [comment]
@JohnKhandygo 
Отправил исправления.
