### ISSUE TITLE
Corrections

### ISSUE THREAD

**Issue by JohnKhandygo** [gnatunstyles/ProkofyevIgnatJavaProject1#6]
Не вижу никаких исправлений. Если Вам что-то не понятно, пишите в комментариях к issue, если для Вас что-то слишком сложно, давайте обсудим, что достаточно сделать на 3. 

В любом случае, напишите, когда задание будет готово к повторной проверке.

**Comment by gnatunstyles** [comment]
@JohnKhandygo 
Извините, что я долго не отправлял вам исправление.
Пофиксил все, что вы мне сказали + добавил javadoc.
Не могли бы вы мне скинуть условие 2 программы, а то из-за моей халатности времени у меня осталось не очень много, а желание приступить к ее изучению огромное?)

**Comment by JohnKhandygo** [comment]
Я не понимаю, над чем Вы собираетесь работать во втором задании, когда Вам до завершения первого еще далековато. Три варианта:
1. Вы закрываете все замечания и получаете оценку 5 - 0.5 (штрафных баллов).
2. Вы закрываете только замечания, связанные с тестами и реализацией, и получаете 4 - 0.5 (штрафных баллов).
3. Я закрываю Вам это задание прямо сейчас, получаете минимальную положительную оценку и следующее задание. 

В общем случае второе задание выдается только после того, как закрыта большая часть замечаний к первому. Сейчас у Вас еще очень много замечаний (и останется немало в случаях 1 и 2), поэтому до второго задания еще далековато. 

Напишите явно, какой вариант Вам больше по душе.

**Comment by gnatunstyles** [comment]
@JohnKhandygo 
Закрыл все замечания, которые Вы мне оставили.
Если замечаний больше нет, скиньте, пожалуйста, второе задание.
Заранее спасибо!

**Comment by JohnKhandygo** [comment]
Второе задание выдано, его проверка начинается не позже завершения первого задания.

**Comment by gnatunstyles** [comment]
@JohnKhandygo 
Закрыл все Ваши замечания к task1.
