### ISSUE TITLE
Task 2.0

### ISSUE THREAD

**Issue by JohnKhandygo** [gnatunstyles/ProkofyevIgnatJavaProject1#7]
**Общая формулировка**
Разработать консольную утилиту, реализующую указанную в задании функциональность, на языках Java и/или Kotlin. При проектировании использовать объектно-ориентированный подход. Разработать автоматические тесты для отдельных частей программы. Написанный код держать в отдельном проекте или модуле в репозитории на GitHub.

**ls**
Вывод содержимого указанной в качестве аргумента директории в виде отсортированного списка имен файлов.
- Флаг -l (long) переключает вывод в длинный формат, в котором, кроме имени файла, указываются права на выполнение/чтение/запись в виде битовой маски XXX, время последней модификации и размер в байтах.
- Флаг -h (human-readable) переключает вывод в человеко-читаемый формат (размер в кило-, мега- или гигабайтах, права на выполнение в виде rwx).
- Флаг -r (reverse) меняет порядок вывода на противоположный.
- Флаг -o (output) указывает имя файла, в который следует вывести результат; если этот флаг отсутствует, результат выводится в консоль.

В случае, если в качестве аргумента указан файл, а не директория, следует вывести информацию об этом файле.

Command Line: ls [-l] [-h] [-r] [-o output.file] directory_or_file

Кроме самой программы, следует написать автоматические тесты к ней.

Также необходимо разработать скрипты и/или инструкции сборки и запуска приложения из командной строки. 

**P.S.** Проверка второго задания начинается не раньше исправления всех замечания к первому заданию. В любом случае напишите в комментариях к этому issue, когда задание будет готово к проверке.

**P.S.S.** Если будете делать это задание в другом репозитории, дайте ссылку в комментариях к этому issue.

**Comment by JohnKhandygo** [comment]
Рекомендуется следующий подход к разработке:
1. Реализовать класс со всей необходимой логикой так, как Вы это делали в предыдущем задании (с покрытием тестами и прочим). Другими словами, забудьте на время, что Ваше приложение должно работать из консоли.
2. Отдельно написать "обертку", которая будет парсить аргументы командной строки (используя библотеку) и вызывать разработанные на первом этапе методы. Скорее всего то, что будет написано на данном этапе даже не потребуется покрывать тестами, поскольку функциональность сторонних библотек обычно не тестируется (либо тестируется в каких-то очень сложных случаях). 

Собственно после готовности первого этапа можно начинать проверку.

**Comment by JohnKhandygo** [comment]
Первое задание зачтено.

**Comment by gnatunstyles** [comment]
@JohnKhandygo 
Готово 2 задание.

**Comment by JohnKhandygo** [comment]
Зачтено на 4.5
