### ISSUE TITLE
Common issues 2.0

### ISSUE THREAD

**Issue by JohnKhandygo** [gnatunstyles/ProkofyevIgnatJavaProject1#8]
- [x] (5) По условию задания:
  > При проектировании использовать объектно-ориентированный подход. 
  
  У Вас же просто один огромный класс, в котором вся логика заключена.
- [x] (3) По условию задания:

  > Также необходимо разработать скрипты и/или инструкции сборки и запуска приложения из командной строки. 

  Я у Вас ничего подобного не вижу.
- [x] (3) Для разбора аргументов командной строки лучше использовать какую-нибудь библиотеку. На лекциях точно рассказывали как минимум про одну такую. Вы, конечно, можете использовать собственную разработку, но тогда:
  - [x] Необходимо генерировать ошибку в случае, если указаны какие-то неизвестные аргументы
  - [x] Флаг с аргументом (в данном случае `-o <out_file_name>`) может располагаться в любом месте командной строки. Текущая реализация ожидает `<out_file_name>` предпоследним аргументом, однако на этом месте может стоять какой-то другой флаг, например.
  - [x] Необходимо покрыть тестами часть кода, отвечающего за разбор аргументов командной строки (включая случаи, в которых ожидается выброс исключения).
- [x] (3) Классы в java принято именовать в UpperCamelCase.
- [x] (3) Некорректно реализован флаг `-r`. Обратный порядок вывода --- это порядок, обратный следованию файлов в папке.

**Comment by gnatunstyles** [comment]
@JohnKhandygo 
К сожалению, до дедлайна по третьей задаче осталось совсем мало времени, а у меня даже условия её как такового нет. Не могли бы Вы сказать, что достаточно сделать на 3 в этой задаче?

**Comment by JohnKhandygo** [comment]
Пометил все пункты оценками: если перед текстом замечания стоит `(x)`, это значит, что исправление этого замечания необходимо для получения оценки `x`. Таким образом, для получения тройки необходимо исправить все комментарии, помеченные как `(3)`.

**Comment by JohnKhandygo** [comment]
Во всех открытых issue все, что не отмечено галочками актуально.
